# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6d68873b7a29b5a10caeb0a6b52f4acf5613ce956a22b297361650f847b8be7f6f4770ada2be45990577b3c5bd0285357fb9c25a02ae85e926dee0756ae5d7b

test:
  secret_key_base: 6d7a3c354576c39d4a9e4cf962189fa60d347fb656735c91bc3d0e4e1d44e5c22e643003aef710371501b6e4176d6e9a101a776462846792facc127ccef57eb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
